name: PHP Composer Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
      
    - name: Run Code Sniffer
      run: composer run-script sniff      

    # - name: Run Linter
      # run: composer run-script lint
      
    - name: Run Static Analysis
      env:
        XDEBUG_MODE: coverage
      run: composer run-script stan    

    # - name: Run Mess Detection
      # run: composer run-script md

    - name: Run Unit Tests
      run: composer run-script test-github

    - name: Upload to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODE_COV }}
        files: ./coverage.xml
        verbose: true